name: Free RDP via Cloudflare (no domain, no card)

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Pass@123" -Force)
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Download Cloudflared
        run: |
          Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe

      - name: Create Tunnel
        run: |
          Start-Process cloudflared.exe -ArgumentList "tunnel --url rdp://localhost:3389" -NoNewWindow
          Write-Host "Starting tunnel..."
          Start-Sleep -Seconds 21600  # 6 hours
